Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
organization_his = (
    df_organizations["form_of_organization"]
    .value_counts()
    .to_frame()
    .rename_axis("organization")
    .reset_index()
)

organization_his["organization"] = organization_his["organization"].apply(upper_string)
fig = px.pie(organization_his, values="form_of_organization", names="organization", color_discrete_sequence=color_discrete_sequence, hole=0.2)

fig.update_layout(title='Distribution of Organisational Forms',font_size=16, showlegend=False, hovermode=False)
fig.update_traces(textposition='outside', textinfo='percent+label', marker=dict(line=dict(color=boarder_color, width=1)))
fig['layout'].update(margin=dict(l=0,r=0,b=50,t=40))
fig.show()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[4], line 13[0m
[1;32m     10[0m fig [38;5;241m=[39m px[38;5;241m.[39mpie(organization_his, values[38;5;241m=[39m[38;5;124m"[39m[38;5;124mform_of_organization[39m[38;5;124m"[39m, names[38;5;241m=[39m[38;5;124m"[39m[38;5;124morganization[39m[38;5;124m"[39m, color_discrete_sequence[38;5;241m=[39mcolor_discrete_sequence, hole[38;5;241m=[39m[38;5;241m0.2[39m)
[1;32m     12[0m fig[38;5;241m.[39mupdate_layout(title[38;5;241m=[39m[38;5;124m'[39m[38;5;124mDistribution of Organisational Forms[39m[38;5;124m'[39m,font_size[38;5;241m=[39m[38;5;241m16[39m, showlegend[38;5;241m=[39m[38;5;28;01mFalse[39;00m, hovermode[38;5;241m=[39m[38;5;28;01mFalse[39;00m)
[0;32m---> 13[0m fig[38;5;241m.[39mupdate_traces(textposition[38;5;241m=[39m[38;5;124m'[39m[38;5;124moutside[39m[38;5;124m'[39m, textinfo[38;5;241m=[39m[38;5;124m'[39m[38;5;124mpercent+label[39m[38;5;124m'[39m, marker[38;5;241m=[39m[38;5;28mdict[39m(line[38;5;241m=[39m[38;5;28mdict[39m(color[38;5;241m=[39m[43mboarder_color[49m, width[38;5;241m=[39m[38;5;241m1[39m)))
[1;32m     14[0m fig[[38;5;124m'[39m[38;5;124mlayout[39m[38;5;124m'[39m][38;5;241m.[39mupdate(margin[38;5;241m=[39m[38;5;28mdict[39m(l[38;5;241m=[39m[38;5;241m0[39m,r[38;5;241m=[39m[38;5;241m0[39m,b[38;5;241m=[39m[38;5;241m50[39m,t[38;5;241m=[39m[38;5;241m40[39m))
[1;32m     15[0m fig[38;5;241m.[39mshow()

[0;31mNameError[0m: name 'boarder_color' is not defined
NameError: name 'boarder_color' is not defined

